//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontLab1.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Painting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Painting()
        {
            this.Painting_Copies = new HashSet<Painting_Copy>();
        }
    
        public int PaintingID { get; set; }
        public string PaintingTitle { get; set; }
        public int SizeID { get; set; }
        public int StatusID { get; set; }
        public string Description { get; set; }
        public string PaintingImg { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Painting_Copy> Painting_Copies { get; set; }
        public virtual Size Size { get; set; }
        public virtual Status Status { get; set; }
    }
}
