//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontLab1.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaintingCopy
    {
        public int CopyID { get; set; }
        public int PaintingID { get; set; }
        public decimal Price { get; set; }
        public int StatusID { get; set; }
        public int SizeID { get; set; }
    
        public virtual Painting Painting { get; set; }
        public virtual Size Size { get; set; }
        public virtual Status Status { get; set; }
    }
}
